theme: jekyll-theme-leap-day
title: Modern Love.
body: 
#"I mean, does anyone have life ‘figured out’?" - Frances in movie "Frances Ha"

#Frances:"It's that thing when you're with someone, and you love them and they know it, and they love you and you know it...

#but it's a party... and you're both talking to other people, and you're laughing and shining...

and you look across the room and catch each other's eyes...but - but not because you're possessive, or it's precisely sexual...

but because... that is your person in this life. And it's funny and sad, but only because this life will end,

and it's this secret world that exists right there in public, unnoticed, that no one else knows about.

It's sort of like how they say that other dimensions exist all around us, but we don't have the ability to perceive them.

That's - That's what I want out of a relationship. Or just life, I guess."

Remembere the scene when Frances was running and dancing across streets with an uninhibitedly sunny smile?

Can you feel her pain and joy altogether at once? 
